name: expression implementation
on: push
env:
  appName: CounterApp
jobs:
  build_job:
    runs-on: windows-latest
    steps:
      - name: Cache
        uses: actions/cache@v1.2.1
        with:
          # A directory to store and save the cache
          path: |
            %USERPROFILE%
          # An explicit key for restoring and saving the cache
          key: |
            cachekey
