name: GitHub Actions Reusable Workflow
run-name: GitHub Actions Reusable Workflow
on: 
  workflow_dispatch:
  workflow_call:
jobs:
  Basic-Workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Execute Reusable Workflow"
